### ISSUE TITLE
plan for code release?

### ISSUE THREAD

**Issue by DietDietDiet** [ankanbhunia/Handwriting-Transformers#1]
Hi, many thanks for your innovative work, just wondering is there a plan for code release? thanks

**Comment by zdaiot** [comment]
> Hi, many thanks for your innovative work, just wondering is there a plan for code release? thanks

I'm interested in this, too.

**Comment by Yuying-W** [comment]
Hi, I am super interested in this great work. But I am wondering is the code release completed?
