### ISSUE TITLE
‘base_path = '../IAM_32.pickle'’ 

### ISSUE THREAD

**Issue by zj916716524** [ankanbhunia/Handwriting-Transformers#4]
Hello, what's in your code ‘base_path = '../IAM_32.pickle'’ 。Can this document be published? If so, please send me a private letter? Thanks for your reading！

**Comment by kientuongnguyen** [comment]
@ankanbhunia Same question, will you publish this file, or at least, its structure?

**Comment by ankanbhunia** [comment]
https://drive.google.com/file/d/1KtD2e3GTb1Of-xeH-oTQQWf8Atyne3-2/view?usp=sharing
