### ISSUE TITLE
No such file or directory: '../CVL_32.pickle'

### ISSUE THREAD

**Issue by kientuongnguyen** [ankanbhunia/Handwriting-Transformers#5]
Thank you for publishing `IAM_32.pickle` in Issue #4 
I cloned this project to my personal Colab Notebook and executed "train.py". Now the file `CVL_32.pickle` is required.

```
Traceback (most recent call last):
  File "./Handwriting-Transformers/train.py", line 42, in <module>
    TextDatasetObjval = TextDatasetval()
  File "/content/Handwriting-Transformers/data/dataset.py", line 109, in __init__
    file_to_store = open(base_path, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '../CVL_32.pickle'
```
Would you please publish this file also?

Thank you very much. 🙇

**Comment by engrean** [comment]
I'm not sure if this helps, but it does look the developer provided the link to this file in issue #4 which was marked as closed:
https://github.com/ankanbhunia/Handwriting-Transformers/issues/4

**Comment by wangwenhaoxiaotie** [comment]
Hello, Do you know where is  '../Lexicon/english_words.txt'?

**Comment by miranghimire** [comment]
> Hello, Do you know where is '../Lexicon/english_words.txt'?

Any updates here or idea how it is generated, stuck in the same scenario?

**Comment by maozan** [comment]
> Hello, Do you know where is '../Lexicon/english_words.txt'?

Hello, Do you have the file '../Lexicon/english_words.txt'?

**Comment by ankanbhunia** [comment]
Please refer to the install.md
