### ISSUE TITLE
About pre-trained model.

### ISSUE THREAD

**Issue by Fyzjym** [ankanbhunia/Handwriting-Transformers#6]
Sir, the method proposed in your paper has effectively improved.
I am very curious how to get the "fid: four scenes" in your paper
In addition,  Would you like to share the pre-trained model.
I am sorry for my recklessness.
good luck.

**Comment by Fyzjym** [comment]
I noticed that your method is much better than Ganwriting on Fid. But neither of these two papers detailed how to calculate Fid.
Did I miss anything?
Hope to get your guidance.
@ankanbhunia

**Comment by ankanbhunia** [comment]
see install.md.
