### ISSUE TITLE
CVL_32.pickle

### ISSUE THREAD

**Issue by xuruiying** [ankanbhunia/Handwriting-Transformers#7]
Hello, what's in your code ‘base_path = './CVL_32.pickle'’ 。Can this document be published? If so, please send me a private letter? Thanks for your reading

**Comment by Fyzjym** [comment]
Hello sir, I don’t have this data set either.
Excuse me, have you got it?
Would you like to send me a data set?

**Comment by ankanbhunia** [comment]
Its added and described in install.md file.
